### ISSUE TITLE
A script and some tips for MakeCode coding in Minecraft Bedrock for Windows 10 and 11 with Code Connection and CodeConnectionFix

### ISSUE THREAD

**Issue by Vegz78** [lrocher/CodeConnectFix#5]
Hi @lrocher,

Just wanted to tip you about this:
https://github.com/Vegz78/CodeConnectFix-Tips-Troubleshooting

Do whatever you want with it or not.

Thanks for a great workaround with CodeConnectFix to enable coding with MakeCode in Minecraft Bedrock Edition while we all are still waiting for the [MCPE-154405](https://bugs.mojang.com/browse/MCPE-154405) bug from April the 19th 2022 to be fixed!...

**Comment by lrocher** [comment]
Thank you for the tips.
Happy to see it help you also.
