### ISSUE TITLE
Installer for CodeConnection

### ISSUE THREAD

**Issue by minecraft-dad** [lrocher/CodeConnectFix#7]
Hello, I don't know how else to contact you so pardon for this issue.
Could you share an installer for the Code Connection app? I am unable to find any other public links.

I saw your post on the MakeCode forum, but the link was no longer available.
Thank you!

**Comment by VanillaBase** [comment]
the internet archive can download it.type the download link into it and select 2019,and u can download it.

**Comment by minecraft-dad** [comment]
I actually found another link.
Thanks and let me close this issue
